# Site settings
title: Hugo Chou å‘¨æ˜Œæƒ | ðŸ¡ My Home on the Web
author: Hugo Chou å‘¨æ˜Œæƒ
email: hugochougt@gmail.com
url: https://hugochougt.com
repo: https://github.com/hugochougt/hugochougt.github.io
baseurl: ""
description: >
  A software engineer with 10+ years of experience in commercial application and software development. I've launched over 20 applications, including iOS and Android apps, WeChat Mini Programs, and Web sites.
lang: zh-CN
permalink: /blog/:title
date_format: "%Y-%m-%d"

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
